/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HMS;

import com.toedter.calendar.JCalendar;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mizanur Rahman
 */
public class Bil_Detailsl extends javax.swing.JFrame {

    /**
     * Creates new form Bil_Detailsl
     */
    public Bil_Detailsl() {
        initComponents();
        cuDate();
        String m="SELECT `id` FROM `bill` ORDER BY `id` ASC";
        txtbill.setText("HMS00M-"+autoid(m));
        DatasetCombo();
        panelID1.setText("HMS00M-"+autoid(m));
        txtpartid.setText(""+autoid("SELECT `pid` FROM `particular_info` ORDER BY `pid` ASC"));
        
        
        
        
    }
     Connection con=null;
Statement st=null;
PreparedStatement pst=null;
ResultSet rs=null;

    void Myconnect(){

        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital_management","root","");
           
        } catch (SQLException ex) {
            Logger.getLogger(MyConnection.class.getName()).log(Level.SEVERE, null, ex);
        }
}
//All Method
     void cuDate(){
         JCalendar d=new JCalendar();
         SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
            String mm=sd.format(d.getDate());
       panelDate.setText(mm);
        
    }
      int autoid(String m){
        int a = 0;
        try {
            
           Myconnect();
            
            pst=con.prepareStatement(m);
            rs=pst.executeQuery();
            while(rs.next()){
                a=rs.getInt(1);
                
                
            }
            a++;
        } catch (SQLException ex) {
            Logger.getLogger(Bil_Detailsl.class.getName()).log(Level.SEVERE, null, ex);
        }
        return a;
    }
      void DatasetCombo(){
        try {
            Myconnect();
            txtpart.removeAllItems();
            txtpart.addItem("Select Particulars");
            String m="SELECT `name` FROM `particular_info`";
            pst=con.prepareStatement(m);
            rs=pst.executeQuery();
            while(rs.next()){
                txtpart.addItem(rs.getString(1));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Bil_Detailsl.class.getName()).log(Level.SEVERE, null, ex);
        }
          
      }
      String date;
      void setPatientData(){
        try {
            Myconnect();
            String id=txtpid.getText().toString();
            String m="SELECT `fname`,`age`,`room`,`date` FROM `patient_details` WHERE `pid`=?";
            pst=con.prepareStatement(m);
            pst.setString(1,id);
            rs=pst.executeQuery();
            if(rs.next()){
                txtpname.setText(rs.getString(1));
                txtage.setText(rs.getString(2));
                panelpatient.setText(rs.getString(1));
                //txtprice.setText(rs.getString(3));
                panelroom.setText(rs.getString(3));
                date=rs.getString(4);
                panelID.setText(id);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Bil_Detailsl.class.getName()).log(Level.SEVERE, null, ex);
        }
          
      }
      void Showparti(){
        try {
            Myconnect();
            DefaultTableModel dt=(DefaultTableModel)jTable2.getModel();
            dt.setRowCount(0);
            String m="SELECT *FROM `particular_info`";
            pst=con.prepareStatement(m);
            rs=pst.executeQuery();
            while(rs.next()){
                dt.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Bil_Detailsl.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        search = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelDate = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtsub = new javax.swing.JLabel();
        txtto = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        due = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        panelroom = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtdisco = new javax.swing.JTextField();
        txttotal = new javax.swing.JLabel();
        due2 = new javax.swing.JLabel();
        due3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        panelID1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelID = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelpatient = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtlab = new javax.swing.JLabel();
        txtpharmecy = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtpname = new javax.swing.JTextField();
        txtquant = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtbill = new javax.swing.JTextField();
        txtpart = new javax.swing.JComboBox();
        txtpid = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtpartid = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtpartprice = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtpartname = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setOpaque(true);

        jPanel1.setLayout(null);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(310, 620, 0, 0);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("EDIT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 550, 90, 30);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(320, 550, 100, 30);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Exit");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(120, 600, 100, 30);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS/picture/DepartmentPicture/icons8_send_to_printer_20px.png"))); // NOI18N
        jButton5.setText("PRINT");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(260, 600, 100, 30);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(837, 99, 270, 0);

        search.setBackground(new java.awt.Color(102, 102, 102));
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });
        jPanel3.add(search);
        search.setBounds(1070, 60, 180, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS/picture/DepartmentPicture/icons8_search_30px_2.png"))); // NOI18N
        jPanel3.add(jLabel15);
        jLabel15.setBounds(1040, 60, 30, 40);

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("hospital billing");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(170, 30, 530, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(-170, 0, 700, 110);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL.No", "Particulars Name", "Quantity", "Price", "Total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(40, 240, 590, 260);
        jPanel5.add(panelDate);
        panelDate.setBounds(504, 160, 110, 30);

        jLabel24.setText("Subtotal:");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(460, 500, 50, 30);

        txtsub.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel5.add(txtsub);
        txtsub.setBounds(550, 500, 60, 30);
        jPanel5.add(txtto);
        txtto.setBounds(550, 580, 90, 20);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setText("Total Amount:");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(460, 630, 90, 30);

        due.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        due.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        due.setText("/=");
        jPanel5.add(due);
        due.setBounds(630, 630, 20, 30);
        jPanel5.add(jSeparator1);
        jSeparator1.setBounds(78, 48, 467, 0);

        jLabel30.setText("Room no:");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(430, 190, 70, 30);
        jPanel5.add(panelroom);
        panelroom.setBounds(490, 190, 60, 30);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel5.add(jButton4);
        jButton4.setBounds(-70, 120, 40, 40);

        jLabel11.setText("Discount:");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(460, 600, 70, 20);

        txtdisco.setBackground(new java.awt.Color(240, 240, 240));
        txtdisco.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtdisco.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        txtdisco.setOpaque(false);
        txtdisco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdiscoKeyPressed(evt);
            }
        });
        jPanel5.add(txtdisco);
        txtdisco.setBounds(550, 600, 90, 20);

        txttotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txttotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(txttotal);
        txttotal.setBounds(560, 630, 70, 30);

        due2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        due2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        due2.setText("-----------------------------------------------");
        jPanel5.add(due2);
        due2.setBounds(410, 610, 250, 30);

        due3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        due3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        due3.setText("-----------------------------------------------");
        jPanel5.add(due3);
        due3.setBounds(390, 560, 280, 30);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);
        jPanel6.add(panelID1);
        panelID1.setBounds(60, 0, 110, 20);

        jLabel8.setText("Bill No:");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(10, 0, 60, 20);

        jLabel9.setText("Patient ID:");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(10, 30, 60, 20);
        jPanel6.add(panelID);
        panelID.setBounds(70, 30, 47, 20);

        jLabel12.setText("Patient Name:");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(10, 60, 80, 30);

        panelpatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel6.add(panelpatient);
        panelpatient.setBounds(90, 60, 150, 30);

        jLabel23.setText("Age:");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(220, 0, 36, 20);
        jPanel6.add(txtage);
        txtage.setBounds(260, 0, 50, 20);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(70, 120, 300, 90);

        jLabel7.setText("Pharmecy Due:");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(460, 530, 90, 20);

        jLabel20.setText("Lab Due:");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(460, 550, 70, 20);

        jLabel27.setText("Total:");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(460, 580, 40, 20);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel28.setText("Hope Hospital Pvt. Ltd");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(240, 20, 200, 30);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel29.setText("Bangodda Bazzer,Nangolkot,Comilla");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(270, 40, 310, 30);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel31.setText("Mobile:01645316379,E-mail:mizan81025@gmail.com");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(230, 60, 320, 30);
        jPanel5.add(txtlab);
        txtlab.setBounds(550, 550, 70, 20);
        jPanel5.add(txtpharmecy);
        txtpharmecy.setBounds(550, 530, 70, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab_Info/Test_pic.jpg"))); // NOI18N
        jPanel5.add(jLabel16);
        jLabel16.setBounds(0, 10, 650, 710);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(540, 0, 650, 720);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patients Bill Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Patient ID:");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(100, 110, 70, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Patient Name:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(100, 160, 80, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Particulars:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(100, 220, 70, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Bill No:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(100, 60, 50, 40);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Quantity:");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(100, 330, 80, 30);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel32.setText("Price:");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(100, 280, 80, 40);

        txtpname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(txtpname);
        txtpname.setBounds(190, 160, 260, 40);

        txtquant.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtquant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtquantMouseClicked(evt);
            }
        });
        jPanel4.add(txtquant);
        txtquant.setBounds(190, 330, 260, 40);

        txtprice.setEditable(false);
        txtprice.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(txtprice);
        txtprice.setBounds(190, 280, 260, 40);

        txtbill.setEditable(false);
        txtbill.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(txtbill);
        txtbill.setBounds(190, 60, 260, 40);

        txtpart.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtpart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtpart.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                txtpartPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel4.add(txtpart);
        txtpart.setBounds(190, 220, 260, 40);

        txtpid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(txtpid);
        txtpid.setBounds(190, 110, 260, 40);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS/picture/DepartmentPicture/icons8_ok_20px_1.png"))); // NOI18N
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);
        jButton12.setBounds(450, 110, 40, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 140, 500, 390);

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setText("Save");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(80, 550, 90, 30);

        jTabbedPane1.addTab("Bill Details", jPanel1);

        jPanel2.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ADD PARTICULARS INFO");
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel2.add(jLabel17);
        jLabel17.setBounds(320, 10, 690, 70);

        jLabel18.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setText("Particular Name:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(150, 270, 120, 30);
        jPanel2.add(txtpartid);
        txtpartid.setBounds(270, 200, 230, 40);
        jPanel2.add(jLabel19);
        jLabel19.setBounds(370, 270, 0, 10);
        jPanel2.add(txtpartprice);
        txtpartprice.setBounds(270, 330, 230, 40);

        jLabel22.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 51));
        jLabel22.setText("Price:");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(160, 330, 80, 30);

        jLabel21.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setText("Particulars ID :");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(150, 210, 110, 20);
        jPanel2.add(txtpartname);
        txtpartname.setBounds(270, 260, 230, 40);

        jButton6.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jButton6.setText("Edit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(290, 440, 100, 29);

        jButton7.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(410, 440, 130, 29);

        jButton8.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jButton8.setText("Exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(430, 490, 100, 29);

        jButton9.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jButton9.setText("Add");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(170, 440, 100, 29);

        jButton10.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jButton10.setText("Clear");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(320, 490, 100, 29);

        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Particulars Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 170, 620, 240);

        jTable2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Particular Id", "Particular Name", "price"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(690, 180, 560, 402);

        jButton13.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS/picture/DepartmentPicture/icons8_refresh_25px.png"))); // NOI18N
        jButton13.setText("Refresh");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13);
        jButton13.setBounds(170, 490, 140, 30);

        jLabel2.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS/picture/DepartmentPicture/Bill.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 800);

        jTabbedPane1.addTab("Bill info add", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 1370, 740);

        setBounds(0, 0, 1384, 775);
    }// </editor-fold>//GEN-END:initComponents

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        search.setText("");
    }//GEN-LAST:event_searchMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // Search pressed enter key
        

    }//GEN-LAST:event_searchKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
       
        txtquant.setText(d.getValueAt(jTable1.getSelectedRow(), 2).toString());
         txtprice.setText(d.getValueAt(jTable1.getSelectedRow(), 3).toString());
       
        String m;
        m = d.getValueAt(jTable1.getSelectedRow(), 1).toString();
       
        sb.SelectedTablevaluesetTable(m,txtpart);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        setPatientData();
        String a=txtpid.getText();
        sb.findphar(txtpharmecy, a);
        sb.findlab(txtlab, a);
    }//GEN-LAST:event_jButton12ActionPerformed

 
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            // TODO add your handling code here:
            Myconnect();
            String mpartid=txtpartid.getText().toString();
            
            String name=txtpartname.getText().toString();
            String price=txtpartprice.getText().toString();
            String m="INSERT INTO `particular_info` VALUES (?,?,?)";
            pst=con.prepareStatement(m);
            pst.setString(1, mpartid);
            pst.setString(2, name);
            pst.setString(3, price);
            int a=pst.executeUpdate();
            if(a>0){
                JOptionPane.showMessageDialog(this, "Added Succesful!");
                ClearPart();
                Showparti();
                 DatasetCombo();
            }
            else{
                JOptionPane.showMessageDialog(this, "Cannot Added!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Bil_Detailsl.class.getName()).log(Level.SEVERE, null, ex);
        }
           
           
    }//GEN-LAST:event_jButton9ActionPerformed

    void ClearPart(){
          txtpartid.setText("");
                txtpartname.setText("");
                txtpartprice.setText("");
                  txtpartid.setText(""+autoid("SELECT `pid` FROM `particular_info` ORDER BY `pid` ASC"));
    }
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         Showparti();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        ClearPart();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
         DefaultTableModel dt=(DefaultTableModel)jTable2.getModel();
        txtpartid.setText(dt.getValueAt(jTable2.getSelectedRow(),0).toString());
        txtpartname.setText(dt.getValueAt(jTable2.getSelectedRow(),1).toString());
         txtpartprice.setText(dt.getValueAt(jTable2.getSelectedRow(),2).toString());
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Particular update
         try {
            // TODO add your handling code here:
            Myconnect();
            String mpartid=txtpartid.getText().toString();
            
            String name=txtpartname.getText().toString();
            String price=txtpartprice.getText().toString();
            String m="UPDATE `particular_info` SET `name`='"+name+"',`price`='"+price+"' WHERE `pid`='"+mpartid+"'";
            pst=con.prepareStatement(m);
           // pst.setString(1, mpartid);
          
            int a=pst.executeUpdate();
            if(a>0){
                JOptionPane.showMessageDialog(this, "update Succesful!");
                ClearPart();
                Showparti();
            }
            else{
                JOptionPane.showMessageDialog(this, "Cannot update!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Bil_Detailsl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Myconnect();
            String mpartid=txtpartid.getText().toString();
            
          
            String m="DELETE FROM `particular_info` WHERE `pid`=?";
            pst=con.prepareStatement(m);
            pst.setString(1, mpartid);
           
            int a=pst.executeUpdate();
            if(a>0){
                JOptionPane.showMessageDialog(this, "Delete Succesful!");
                ClearPart();
                Showparti();
            }
            else{
                JOptionPane.showMessageDialog(this, "Cannot Delete!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Bil_Detailsl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtpartPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_txtpartPopupMenuWillBecomeInvisible
        try {
            // TODO add your handling code here:
            
            Myconnect();
            String name=txtpart.getSelectedItem().toString();
            String m="SELECT `price` FROM `particular_info` WHERE `name`=?";
            pst=con.prepareStatement(m);
            pst.setString(1, name);
            rs=pst.executeQuery();
            while(rs.next()){
                txtprice.setText(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Bil_Detailsl.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtquant.requestFocus();
        
    }//GEN-LAST:event_txtpartPopupMenuWillBecomeInvisible

    Sub_Bill sb=new Sub_Bill();
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String bill=txtbill.getText().toString();
        String name=txtpname.getText().toString();
        String id=txtpid.getText().toString();
        String quant=txtquant.getText().toString();
        String price=txtprice.getText().toString();
        String date=panelDate.getText().toString();
        String part=txtpart.getSelectedItem().toString();
        String m="INSERT INTO `part_record`(`bil_id`,`pname`,`pid`,`quant`,`price`,`date`,`particular`) VALUES ('"+bill+"','"+name+"','"+id+"','"+quant+"','"+price+"','"+date+"','"+part+"')";
        sb.dataoperation(m);
        sb.ShowDataTable(jTable1,bill,txtsub);
        if(txtpharmecy.getText()!="" && txtlab.getText()!=""){
            int a=Integer.parseInt(txtpharmecy.getText());
            int b=Integer.parseInt(txtlab.getText());
            int c=Integer.parseInt(txtsub.getText());
            int s=a+b+c;
            txtto.setText(""+s);
            
        }
        else if(txtpharmecy.getText()!="" && txtlab.getText()=="" ){
            int a=Integer.parseInt(txtpharmecy.getText());
            //int b=Integer.parseInt(txtlab.getText());
            int c=Integer.parseInt(txtsub.getText());
            int s=a+c;
            txtto.setText(""+s);
            
        }
        else if(txtlab.getText()!="" && txtpharmecy.getText()==""){
            //int a=Integer.parseInt(txtpharmecy.getText());
            int b=Integer.parseInt(txtlab.getText());
            int c=Integer.parseInt(txtsub.getText());
            int s=b+c;
            txtto.setText(""+s);
            
        }
        else{
            
             int c=Integer.parseInt(txtsub.getText());
            txtto.setText(""+c);
            
            
        }
        
        
        
        
        
        txtpart.setSelectedIndex(0);
        txtquant.setText("");
        txtprice.setText("");
        
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String bill=txtbill.getText().toString();
       
        String quant=txtquant.getText().toString();
        String price=txtprice.getText().toString();
       
        String part=txtpart.getSelectedItem().toString();
        String m="UPDATE `part_record` SET `particular`='"+part+"',`quant`='"+quant+"',`price`='"+price+"' WHERE `bil_id`='"+bill+"' AND `particular`='"+part+"'";
         sb.dataoperation(m);
        sb.ShowDataTable(jTable1,bill,txtsub);
        txtpart.setSelectedIndex(0);
        txtquant.setText("");
        txtprice.setText("");
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String bill=txtbill.getText().toString();
         String part=txtpart.getSelectedItem().toString();
         String m="DELETE FROM `part_record` WHERE `bil_id`='"+bill+"' AND `particular`='"+part+"'";
          sb.dataoperation(m);
        sb.ShowDataTable(jTable1,bill,txtsub);
        txtpart.setSelectedIndex(0);
        txtquant.setText("");
        txtprice.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        int a=dt.getRowCount();
        String sub=txtsub.getText().toString();
        String pid=txtpid.getText().toString();
        String name=txtpname.getText();
        String room=panelroom.getText().toString();
        String date=panelDate.getText().toString();
        String dis=txtdisco.getText().toString();
        String total=txttotal.getText().toString();
        String m="INSERT INTO `bill`(`pid`,`pname`,`proom`,`date`,`part_item`,`subtotal`,`discount`,`total`) VALUES ('"+pid+"','"+name+"','"+room+"','"+date+"','"+a+"','"+sub+"','"+dis+"','"+total+"')";
        sb.AddData(m, jTable1);
        sb.printBill(jPanel5);
        sb.UpPhar(pid);
        sb.Uplab(pid);
        Cl_Panel();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    void Cl_Panel(){
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
         String n="SELECT `id` FROM `bill` ORDER BY `id` ASC";
        txtbill.setText("HMS00M-"+autoid(n));
        
        panelID1.setText("HMS00M-"+autoid(n));
        dt.setRowCount(0);
        txttotal.setText("");
        txtdisco.setText("");
       // txtpaid.setText("");
        txtsub.setText("");
        panelpatient.setText("");
        txtage.setText("");
        panelroom.setText("");
        panelID.setText("");
        txtpname.setText("");
        txtpid.setText("");
        txtto.setText("");
        txtlab.setText("");
        txtpharmecy.setText("");
    }
    private void txtdiscoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiscoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            double b=Double.parseDouble(txtto.getText());
            int c=Integer.parseInt(txtdisco.getText());
            double s=b-c;
            txttotal.setText(s+"");
            //txtpaid.requestFocus();
        }
    }//GEN-LAST:event_txtdiscoKeyPressed

    private void txtquantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtquantMouseClicked
        // TODO add your handling code here:
        txtquant.setText("");
    }//GEN-LAST:event_txtquantMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bil_Detailsl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bil_Detailsl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bil_Detailsl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bil_Detailsl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bil_Detailsl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel due;
    private javax.swing.JLabel due2;
    private javax.swing.JLabel due3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel panelDate;
    private javax.swing.JLabel panelID;
    private javax.swing.JLabel panelID1;
    private javax.swing.JLabel panelpatient;
    private javax.swing.JLabel panelroom;
    private javax.swing.JTextField search;
    private javax.swing.JLabel txtage;
    private javax.swing.JTextField txtbill;
    private javax.swing.JTextField txtdisco;
    private javax.swing.JLabel txtlab;
    private javax.swing.JComboBox txtpart;
    private javax.swing.JTextField txtpartid;
    private javax.swing.JTextField txtpartname;
    private javax.swing.JTextField txtpartprice;
    private javax.swing.JLabel txtpharmecy;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtpname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtquant;
    private javax.swing.JLabel txtsub;
    private javax.swing.JLabel txtto;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
