/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab_Info;

import Pharmecy.Sub_Invoic;
import Pharmecy.Timeset;
import com.toedter.calendar.JCalendar;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mizanur Rahman
 */
public class Add_Test extends javax.swing.JFrame {

    /**
     * Creates new form Add_Test
     */
    public Add_Test() {
        initComponents();
        ti.setTime(txttime);
        cuDate(txtdate);
        cuDate(txtdat);
        txtinvoice.setText("HMST-"+st1.autoid());
        txtinvoiceId.setText("HMST-"+st1.autoid());
        st1.selectedCombo(txtmedicine);
    }
     void cuDate(JLabel t){
         JCalendar d=new JCalendar();
         SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
            String mm=sd.format(d.getDate());
      t.setText(mm);
       //si.selectedCombo(txtmedicine);
    }
Timeset ti=new Timeset();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jaflkdsflsadjf = new javax.swing.JLabel();
        txtsubtotal3 = new javax.swing.JLabel();
        txtsubtotal5 = new javax.swing.JLabel();
        txtdisco = new javax.swing.JTextField();
        txtpaid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtdate = new javax.swing.JLabel();
        txtinvoice = new javax.swing.JLabel();
        txtpid = new javax.swing.JLabel();
        txtpname = new javax.swing.JLabel();
        txtdue = new javax.swing.JLabel();
        txttotal = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JLabel();
        txtsubtotal2 = new javax.swing.JLabel();
        txtsubtotal4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txttime = new javax.swing.JLabel();
        txtdat = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        txtmedicine = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txpatientid = new javax.swing.JTextField();
        txtinvoiceId = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jTable4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL.NO", "Test/Exam Name", "Price"
            }
        ));
        jTable4.setGridColor(new java.awt.Color(255, 255, 255));
        jTable4.setShowGrid(false);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable4);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(70, 280, 570, 230);

        jaflkdsflsadjf.setText("/=");
        jPanel1.add(jaflkdsflsadjf);
        jaflkdsflsadjf.setBounds(630, 630, 40, 30);

        txtsubtotal3.setText("/=");
        jPanel1.add(txtsubtotal3);
        txtsubtotal3.setBounds(630, 540, 40, 30);

        txtsubtotal5.setText("/=");
        jPanel1.add(txtsubtotal5);
        txtsubtotal5.setBounds(630, 600, 40, 30);

        txtdisco.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtdisco.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        txtdisco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdiscoKeyPressed(evt);
            }
        });
        jPanel1.add(txtdisco);
        txtdisco.setBounds(560, 540, 100, 30);

        txtpaid.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtpaid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        txtpaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpaidKeyPressed(evt);
            }
        });
        jPanel1.add(txtpaid);
        txtpaid.setBounds(560, 600, 100, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Note:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 520, 60, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("---------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(70, 660, 630, 17);

        jLabel2.setText("Subtotal:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(500, 510, 60, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Total:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(510, 570, 50, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Paid:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(510, 600, 50, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Discount:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(505, 540, 50, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Due:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(510, 630, 50, 30);

        jLabel12.setText("Date:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(420, 180, 30, 20);

        jLabel13.setText("Invoic No:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 160, 70, 30);

        jLabel14.setText("Patient ID:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(70, 190, 70, 30);

        jLabel15.setText("Patient Name:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(70, 220, 80, 30);
        jPanel1.add(txtdate);
        txtdate.setBounds(460, 170, 140, 40);
        jPanel1.add(txtinvoice);
        txtinvoice.setBounds(130, 160, 190, 30);
        jPanel1.add(txtpid);
        txtpid.setBounds(140, 190, 230, 30);
        jPanel1.add(txtpname);
        txtpname.setBounds(160, 220, 150, 30);
        jPanel1.add(txtdue);
        txtdue.setBounds(560, 630, 100, 30);
        jPanel1.add(txttotal);
        txttotal.setBounds(560, 570, 100, 30);
        jPanel1.add(jLabel19);
        jLabel19.setBounds(560, 570, 100, 30);
        jPanel1.add(jLabel27);
        jLabel27.setBounds(560, 570, 100, 30);
        jPanel1.add(txtsubtotal);
        txtsubtotal.setBounds(560, 510, 100, 30);

        txtsubtotal2.setText("/=");
        jPanel1.add(txtsubtotal2);
        txtsubtotal2.setBounds(630, 510, 40, 30);

        txtsubtotal4.setText("/=");
        jPanel1.add(txtsubtotal4);
        txtsubtotal4.setBounds(630, 570, 40, 30);

        jTextArea1.setColumns(10);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(70, 546, 400, 110);

        jPanel2.setBackground(new java.awt.Color(194, 195, 210));
        jPanel2.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab_Info/Bill_test.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(100, 10, 150, 100);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Hope Hospital Pvt. Ltd");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(230, 20, 200, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 153));
        jLabel10.setText("Bangodda Bazzer,Nangolkot,Comilla");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(250, 40, 320, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("Mobile:01645316379,E-mail:mizan81025@gmail.com");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(220, 60, 320, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 20, 580, 120);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("---     ------------------------   ----------------------------- - -----------------------------  ------------- -------");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(60, 140, 600, 17);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab_Info/barcode-306926_640.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(490, 220, 110, 50);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("---------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(60, 144, 630, 17);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel24.setText("Developed By Mizanur Rahman");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(320, 670, 200, 20);

        txttime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txttime);
        txttime.setBounds(550, 200, 50, 20);
        jPanel1.add(txtdat);
        txtdat.setBounds(490, 200, 70, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(530, 0, 710, 710);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel21.setText("Patient ID:");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(130, 220, 70, 30);

        txtprice.setEditable(false);
        jPanel4.add(txtprice);
        txtprice.setBounds(220, 320, 190, 30);

        txtmedicine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtmedicine.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                txtmedicinePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel4.add(txtmedicine);
        txtmedicine.setBounds(220, 270, 190, 30);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel22.setText("Test/Exam Name:");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(120, 270, 90, 30);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel25.setText("Invoice No:");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(130, 170, 90, 30);

        txpatientid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txpatientidMouseClicked(evt);
            }
        });
        jPanel4.add(txpatientid);
        txpatientid.setBounds(220, 220, 190, 30);

        txtinvoiceId.setEditable(false);
        txtinvoiceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinvoiceIdActionPerformed(evt);
            }
        });
        jPanel4.add(txtinvoiceId);
        txtinvoiceId.setBounds(220, 170, 190, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS/picture/DepartmentPicture/icons8_ok_20px_1.png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(410, 220, 40, 30);

        jButton4.setText("SAVE");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(120, 410, 80, 30);

        jButton5.setText("DELETE");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(240, 410, 80, 30);

        jButton6.setText("CLEAR");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(190, 480, 80, 30);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS/picture/DepartmentPicture/icons8_send_to_printer_20px.png"))); // NOI18N
        jButton7.setText("PRINT");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);
        jButton7.setBounds(360, 410, 110, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Test/Exam Invoice");
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        jPanel4.add(jLabel18);
        jLabel18.setBounds(130, 20, 290, 50);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel26.setText("Price:");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(140, 330, 30, 15);

        jLabel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Test/Exam Invoice Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel4.add(jLabel20);
        jLabel20.setBounds(30, 110, 460, 270);

        jButton8.setText("EXIT");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(320, 480, 80, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 10, 500, 700);

        setSize(new java.awt.Dimension(1251, 748));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtdiscoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiscoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            double b=Double.parseDouble(txtsubtotal.getText());
            String m=txtdisco.getText();
            int c=Integer.parseInt(txtdisco.getText());
            double s=b-c;
            txttotal.setText(s+"");
            txtpaid.requestFocus();

        }

    }//GEN-LAST:event_txtdiscoKeyPressed

    private void txtpaidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaidKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            double b=Double.parseDouble(txttotal.getText());
            String m=txtdisco.getText();
            int c=Integer.parseInt(txtpaid.getText());
            double s=b-c;
            txtdue.setText(s+"");
            //txtpaid.requestFocus();
        }
    }//GEN-LAST:event_txtpaidKeyPressed
   Sub_test st1=new Sub_test();
    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dt=(DefaultTableModel)jTable4.getModel();
        //txtid.setText(dt.getValueAt(jTable1.getSelectedRow(), 0).toString());
        String a=(dt.getValueAt(jTable4.getSelectedRow(), 1).toString());
        st1.SelectedTablevaluesetTable(a, txtmedicine);
        //txtname.setText(dt.getValueAt(jTable1.getSelectedRow(), 2).toString());
        txtprice.setText(dt.getValueAt(jTable4.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_jTable4MouseClicked

    private void txtmedicinePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_txtmedicinePopupMenuWillBecomeInvisible
        try {
            String gh=txtpid.getText().toString();
            if(gh.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please!Give Patients Id");
                txtpid.requestFocus();
            }
            else{
            st1.Myconnect();
            // TODO add your handling code here:
            String name=txtmedicine.getSelectedItem().toString();
            String m="SELECT `price` FROM `test_exam` WHERE `name`='"+name+"'";
            st1.rs=st1.st.executeQuery(m);
            //JOptionPane.showMessageDialog(this, "");
            while(st1.rs.next()){
                
                txtprice.setText(st1.rs.getString(1));
               // txtprice1.setText(st.rs.getString(2));
            }}
        } catch (SQLException ex) {
            Logger.getLogger(Add_Test.class.getName()).log(Level.SEVERE, null, ex);
        }
        //txtquant.requestFocus();
        //valueshow.setText("");
        
    }//GEN-LAST:event_txtmedicinePopupMenuWillBecomeInvisible

    private void txpatientidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txpatientidMouseClicked
        // TODO add your handling code here:
        txpatientid.setText("");
    }//GEN-LAST:event_txpatientidMouseClicked

    private void txtinvoiceIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinvoiceIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinvoiceIdActionPerformed
 Sub_Invoic si=new Sub_Invoic();
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String a=txpatientid.getText().toString();
        //String g="";
        String m="SELECT `fname` FROM `patient_details` WHERE `pid`='"+a+"'";
        si.DataSetPanel(txtpname,m);
        txtpid.setText(a);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //String id="";
        // TODO add your handling code here:
        st1.Myconnect();
        String pname=txtmedicine.getSelectedItem().toString();
        //String gp=txtprice1.getText().toString();
        String pid=txtpid.getText().toString();
        // String quant=txtquant.getText().toString();
        String date=txtdate.getText().toString();
        String bill=txtinvoice.getText().toString();
        String price=txtprice.getText().toString();
        String h="INSERT INTO `exam_details`(`pid`,`tname`,`price`,`biil_id`,`tdate`) VALUES ('"+pid+"','"+pname+"','"+price+"','"+bill+"','"+date+"')";
        st1.dataoperation(h);
        String nb="SELECT `tname`,`price` FROM `exam_details` WHERE `biil_id`='"+bill+"'AND `pid`='"+pid+"'";
         st1.ShowDataInTable(nb, jTable4, txtsubtotal);
        txtmedicine.setSelectedIndex(0);
        //txtprice1.setText("");
        txtprice.setText("");
        // txtquant.setText("");

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        st1.Myconnect();
        String pname=txtmedicine.getSelectedItem().toString();
        //String gp=txtprice1.getText().toString();
        String pid=txtpid.getText().toString();
        // String quant=txtquant.getText().toString();
        //String date=txtdate.getText().toString();
        String bill=txtinvoice.getText().toString();
        //String price=txtprice.getText().toString();
        String h="DELETE FROM `exam_details` WHERE `pid`='"+pid+"' AND `tname`='"+pname+"' AND `biil_id`='"+bill+"'";
        st1.dataoperation(h);
        String nb="SELECT `tname`,`price` FROM `exam_details` WHERE `biil_id`='"+bill+"'AND `pid`='"+pid+"'";
        st1.ShowDataInTable(nb, jTable4, txtsubtotal);
        txtmedicine.setSelectedIndex(0);
        //txtprice1.setText("");
        txtprice.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       // Cl_panel();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String date=txtdate.getText().toString();
        String pid=txtpid.getText().toString();
        String name=txtpname.getText().toString();
        
        String total=txttotal.getText().toString();
        String paid=txtpaid.getText().toString();
        String due=txtdue.getText().toString();
        st1.printBill(jPanel1);
        String m="INSERT INTO `test_bill`(`pid`,`pname`,`total`,`paid`,`due`,`tdate`) VALUES('"+pid+"','"+name+"','"+total+"','"+paid+"','"+due+"','"+date+"')";
        st1.AddData(m, jTable4);
       DefaultTableModel dt=(DefaultTableModel)jTable4.getModel();
       dt.setRowCount(0);
          txtinvoice.setText("HMST-"+st1.autoid());
        txtinvoiceId.setText("HMST-"+st1.autoid());
        txtpid.setText("");
        txtpname.setText("");
        txpatientid.setText("");
        txtsubtotal.setText("");
        txttotal.setText("");
        txtdue.setText("");
        txtdisco.setText("");
        //Cl_panel();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jaflkdsflsadjf;
    private javax.swing.JTextField txpatientid;
    private javax.swing.JLabel txtdat;
    private javax.swing.JLabel txtdate;
    private javax.swing.JTextField txtdisco;
    private javax.swing.JLabel txtdue;
    private javax.swing.JLabel txtinvoice;
    private javax.swing.JTextField txtinvoiceId;
    private javax.swing.JComboBox txtmedicine;
    private javax.swing.JTextField txtpaid;
    private javax.swing.JLabel txtpid;
    private javax.swing.JLabel txtpname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JLabel txtsubtotal;
    private javax.swing.JLabel txtsubtotal2;
    private javax.swing.JLabel txtsubtotal3;
    private javax.swing.JLabel txtsubtotal4;
    private javax.swing.JLabel txtsubtotal5;
    private javax.swing.JLabel txttime;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
