/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmecy;

import HMS.Bil_Detailsl;
import HMS.DataOperation;
import HMS.MyConnection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mizanur Rahman
 */
public class Product_info extends javax.swing.JFrame {

    /**
     * Creates new form Product_info
     */
    public Product_info() {
        initComponents();
        getContentPane().setBackground(Color.white);
        String m="SELECT `id` FROM `product_info` ORDER BY `id`ASC";
        txtid.setText(""+autoid(m));
        jTable1.setBackground(Color.white);
    }

   void Cl_panel(){
       txtgp.setSelectedIndex(0);
       txtname.setText("");
       txtprice.setText("");
       String m="SELECT `id` FROM `product_info` ORDER BY `id`ASC";
        txtid.setText(""+autoid(m));
   }
    DataOperation dg=new DataOperation();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtgp = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        search = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Group By:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(710, 120, 80, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Price:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(710, 170, 80, 30);

        txtprice.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txtprice);
        txtprice.setBounds(770, 170, 220, 30);

        txtid.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txtid);
        txtid.setBounds(480, 120, 210, 30);

        txtgp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtgp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Cap", "Syrup", "Injection", "Tablet", "Liquid", "Drops", "Inhalers", "Others" }));
        txtgp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgpActionPerformed(evt);
            }
        });
        getContentPane().add(txtgp);
        txtgp.setBounds(770, 120, 220, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Product ID:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 120, 60, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Product Name:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 170, 80, 30);

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txtname);
        txtname.setBounds(480, 170, 210, 30);

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 90, 680, 130);

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Group By", "Product Name", "Price"
            }
        ));
        jTable1.setShowGrid(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(32, 220, 1220, 350);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(837, 99, 270, 0);

        search.setBackground(new java.awt.Color(102, 102, 102));
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });
        jPanel3.add(search);
        search.setBounds(1060, 40, 180, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS/picture/DepartmentPicture/icons8_search_30px_2.png"))); // NOI18N
        jPanel3.add(jLabel15);
        jLabel15.setBounds(1030, 40, 30, 40);

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Product Information");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(280, 10, 570, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1410, 80);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1050, 110, 90, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("DELETE");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1050, 150, 90, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("VIEW");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1150, 150, 90, 30);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("UPDATE");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1150, 110, 90, 30);

        setSize(new java.awt.Dimension(1279, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // Search pressed enter key
        String id=search.getText();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String m="SELECT `id`,`group`,`name`,`price` FROM `product_info` WHERE `id`='"+id+ "' or `name`='"+id+"'";
       
         ShowData(m);
    Cl_panel();}
    }//GEN-LAST:event_searchKeyPressed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        search.setText("");
    }//GEN-LAST:event_searchMouseClicked

    private void txtgpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String name=txtname.getText();
    String id=txtid.getText();
    String gp=txtgp.getSelectedItem().toString();
    String price=txtprice.getText().toString();
    String m="INSERT INTO `product_info`(`id`,`group`,`name`,`price`) VALUES ('"+id+"','"+gp+"','"+name+"','"+price+"')";
    dg.dataoperation(m);
    String n="SELECT `id`,`group`,`name`,`price` FROM `product_info`";
    ShowData(n);
    Cl_panel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String n="SELECT `id`,`group`,`name`,`price` FROM `product_info`";
    ShowData(n);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String name=txtname.getText();
    String id=txtid.getText();
    String gp=txtgp.getSelectedItem().toString();
    String price=txtprice.getText().toString();
        
        String m="UPDATE `product_info` SET `name`='"+name+"',`group`='"+gp+"',`price`='"+price+"' WHERE `id`='"+id+"'";
    dg.dataoperation(m);
    String n="SELECT `id`,`group`,`name`,`price` FROM `product_info`";
    ShowData(n);
    Cl_panel();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        txtid.setText(dt.getValueAt(jTable1.getSelectedRow(), 0).toString());
        String a=(dt.getValueAt(jTable1.getSelectedRow(), 1).toString());
        valuset(a,txtgp);
        txtname.setText(dt.getValueAt(jTable1.getSelectedRow(), 2).toString());
        txtprice.setText(dt.getValueAt(jTable1.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String id=txtid.getText();
        String m="DELETE FROM `product_info` WHERE `id`='"+id+"'";
         dg.dataoperation(m);
    String n="SELECT `id`,`group`,`name`,`price` FROM `product_info`";
    ShowData(n);
    Cl_panel();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void valuset(String a,JComboBox label){
          int p=0;
       int b=label.getItemCount();
        for (int i = 0; i !=b; i++) {
            String m=label.getItemAt(i).toString();
            if(m.contains(a))
            {
               p=i; 
                
            }
            
        }
      label .setSelectedIndex(p);
       
    }
     public int autoid(String m){
        int a = 0;
        try {
            
           Myconnect();
            
           
            rs=pst.executeQuery(m);
            while(rs.next()){
                a=rs.getInt(1);
                
                
            }
            a++;
        } catch (SQLException ex) {
            Logger.getLogger(Product_info.class.getName()).log(Level.SEVERE, null, ex);
        }
        return a;
    }
        void ShowData(String m){
            Myconnect();
              DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
              dt.setRowCount(0);
            
        try {
            rs=pst.executeQuery(m);
            while(rs.next()){
              dt.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
            }
            Cl_panel();
        } catch (SQLException ex) {
            Logger.getLogger(Product_info.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
        }

     Connection con=null;
  Statement pst=null;
    ResultSet rs=null;
    void Myconnect(){

        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital_management","root","");
            pst=con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(MyConnection.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField search;
    private javax.swing.JComboBox txtgp;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
