/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmecy;
import HMS.DataOperation;
import HMS.MyConnection;
import com.toedter.calendar.JCalendar;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Mizanur Rahman
 */
public class Purchase_Info extends javax.swing.JFrame {

    /**
     * Creates new form Purchase_Info
     */
    public Purchase_Info() {
        initComponents();
        setProductname();
        String m="SELECT `puid` FROM `purchase_info` ORDER BY `puid` ASC ";
        txtpid.setText(pi.autoid(m)+"");
         setCudate();
        
    }

    DataOperation dt=new DataOperation();
    
     Connection con=null;
  public Statement pst=null,st=null;
    ResultSet rs=null,rs2=null;
    //ResultSet rs2=null;
   public void Myconnect(){

        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital_management","root","");
            pst=con.createStatement();
            st=con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(MyConnection.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    void setProductname(){
        try {
            txtname.removeAllItems();
            txtname.addItem("Select product name");
            Myconnect();
            String m="SELECT `name` FROM `product_info`";
            rs=pst.executeQuery(m);
            while(rs.next()){
                txtname.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Purchase_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    Product_info pi=new Product_info();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        search = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtname = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();
        txtquant = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        txtdate = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtgp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Purchase ID", "Product Name", "Group Name", "Quantity", "Price", "Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(520, 120, 760, 520);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(837, 99, 270, 0);

        search.setBackground(new java.awt.Color(102, 102, 102));
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });
        jPanel3.add(search);
        search.setBounds(1060, 70, 180, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HMS/picture/DepartmentPicture/icons8_search_30px_2.png"))); // NOI18N
        jPanel3.add(jLabel15);
        jLabel15.setBounds(1030, 70, 30, 40);

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Purchase Information");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(280, 30, 620, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1410, 120);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Purchase Info"));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Product Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 110, 90, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Group Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 160, 90, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Price:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 270, 50, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Purchase ID:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 50, 90, 30);

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtname.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                txtnamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(txtname);
        txtname.setBounds(200, 110, 230, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Quantity:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 220, 70, 30);

        txtpid.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtpid);
        txtpid.setBounds(200, 50, 230, 40);

        txtquant.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtquant);
        txtquant.setBounds(200, 220, 230, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Date:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 320, 50, 30);

        txtprice.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtprice);
        txtprice.setBounds(200, 270, 230, 40);
        jPanel1.add(txtdate);
        txtdate.setBounds(200, 320, 230, 40);

        jButton4.setText("ADD");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(160, 400, 90, 30);

        jButton5.setText("EDIT");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(260, 400, 90, 30);

        jButton1.setText("DELETE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(360, 400, 90, 30);

        jButton2.setText("VIEW");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(300, 460, 90, 30);

        jButton3.setText("EXIT");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(200, 460, 90, 30);

        txtgp.setEditable(false);
        jPanel1.add(txtgp);
        txtgp.setBounds(200, 160, 230, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 120, 520, 520);

        setSize(new java.awt.Dimension(1294, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //Table selected item show in textfield
        DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
        txtpid.setText(d.getValueAt(jTable1.getSelectedRow(), 0).toString());
        txtprice.setText(d.getValueAt(jTable1.getSelectedRow(), 4).toString());
        //sid.setText(panelID.getText());
        String uu=(d.getValueAt(jTable1.getSelectedRow(), 5).toString());
        ((JTextField)txtdate.getDateEditor().getUiComponent()).setText(uu);
        txtgp.setText(d.getValueAt(jTable1.getSelectedRow(), 2).toString());
        txtquant.setText(d.getValueAt(jTable1.getSelectedRow(), 3).toString());
       
       
        String m =(d.getValueAt(jTable1.getSelectedRow(), 1).toString());
        //JOptionPane.showMessageDialog(this, m);
        //JOptionPane.showMessageDialog(this, j);
        pi.valuset(m,txtname);
        //pi.valuset(y,txtgp);
        
        //pid.setText(""+pidsetData(m));

    }//GEN-LAST:event_jTable1MouseClicked
 void setCudate(){
     JCalendar jc=new JCalendar();
      SimpleDateFormat sm=new SimpleDateFormat("yyyy-MM-dd");
        String mm=sm.format(jc.getDate());
        ((JTextField)txtdate.getDateEditor().getUiComponent()).setText(mm);
 }
    void  Cl_panel(){
        txtgp.setText("");
       txtname.setSelectedIndex(0);
       txtprice.setText("");
       txtquant.setText("");
       
         String m="SELECT `puid` FROM `purchase_info` ORDER BY `puid` ASC ";
        txtpid.setText(pi.autoid(m)+"");
        JCalendar jc=new JCalendar();
        SimpleDateFormat sm=new SimpleDateFormat("yyyy-MM-dd");
        String mm=sm.format(jc.getDate());
        ((JTextField)txtdate.getDateEditor().getUiComponent()).setText(mm);
        //jLabel8.setText(mm);
    }
     String setNameInTable(String m){
       String mm=null;
        try {
            Myconnect();
            
            String name="SELECT `name` FROM `product_info` WHERE `id`='"+m+"'";
            rs2=st.executeQuery(name);
            if(rs2.next())
            {
                mm=(rs2.getString(1));
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Purchase_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        return mm;
        
    }
    void ShowData(String m){
        Myconnect();
        //String j;
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        dt.setRowCount(0);
        //Myconnect();
        try {
            rs=pst.executeQuery(m);
            while(rs.next()){
                 
           
           String ss=setNameInTable(rs.getString(2));
            
                dt.addRow(new Object[]{rs.getString(1),ss,rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
            }
            Cl_panel();
        } catch (SQLException ex) {
            Logger.getLogger(Product_info.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
            
    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        search.setText("");
    }//GEN-LAST:event_searchMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // Search pressed enter key
        String id=search.getText();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String m="SELECT *FROM `purchase_info` WHERE `puid`= '"+id+"'";

            ShowData(m);
            Cl_panel();}
    }//GEN-LAST:event_searchKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String nameid="";
            // TODO add your handling code here:
            String name=txtname.getSelectedItem().toString();
            String h="SELECT `id` FROM `product_info` WHERE `name`='"+name+"'";
            rs=pst.executeQuery(h);
            if(rs.next()){
                nameid=rs.getString(1);
            }
            String id=txtpid.getText();
            String gp=txtgp.getText().toString();
            String price=txtprice.getText().toString();
             SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
            String mm=sd.format(txtdate.getDate());
             String quant=txtquant.getText().toString();
             
             String m="INSERT INTO `purchase_info` VALUES ('"+id+"','"+nameid+"','"+gp+"','"+quant+"','"+price+"','"+mm+"')";
             dt.dataoperation(m);
             String n="SELECT *FROM `purchase_info`";
        ShowData(n);
        } catch (SQLException ex) {
            Logger.getLogger(Purchase_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String m="SELECT *FROM `purchase_info`";
        ShowData(m);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtnamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_txtnamePopupMenuWillBecomeInvisible
        try {
            // TODO add your handling code here:
            Myconnect();
            String a=txtname.getSelectedItem().toString();
            String m="SELECT `group` FROM `product_info` WHERE `name`='"+a+"'";
            rs=pst.executeQuery(m);
            if(rs.next()){
                txtgp.setText(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Purchase_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_txtnamePopupMenuWillBecomeInvisible

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            Myconnect();
            String nameid="";
            // TODO add your handling code here:
            String name=txtname.getSelectedItem().toString();
            String h="SELECT `id` FROM `product_info` WHERE `name`='"+name+"'";
            rs=pst.executeQuery(h);
            if(rs.next()){
                nameid=rs.getString(1);
            }
            String id=txtpid.getText();
            String gp=txtgp.getText().toString();
            String price=txtprice.getText().toString();
            
            String quant=txtquant.getText().toString();
            
            String m="UPDATE `purchase_info` SET `pname`='"+nameid+"',`group`='"+gp+"',`quant`='"+quant+"',`price`='"+price+"' WHERE `puid`='"+id+"'";
            dt.dataoperation(m);
            String n="SELECT *FROM `purchase_info`";
            ShowData(n);
        } catch (SQLException ex) {
            Logger.getLogger(Purchase_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String id=txtpid.getText();
         String m="DELETE FROM `purchase_info` WHERE `puid`='"+id+"'";
         dt.dataoperation(m);
         String n="SELECT *FROM `purchase_info`";
         ShowData(n);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField search;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtgp;
    private javax.swing.JComboBox txtname;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtquant;
    // End of variables declaration//GEN-END:variables
}
